// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var PeerSocketMessage = exports.PeerSocketMessage = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

definePeerSocketMessage()

function definePeerSocketMessage () {
  var enc = [
    encodings.string,
    encodings.bytes
  ]

  PeerSocketMessage.encodingLength = encodingLength
  PeerSocketMessage.encode = encode
  PeerSocketMessage.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.contentType)) {
      var len = enc[0].encodingLength(obj.contentType)
      length += 1 + len
    }
    if (!defined(obj.payload)) throw new Error("payload is required")
    var len = enc[1].encodingLength(obj.payload)
    length += 1 + len
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.contentType)) {
      buf[offset++] = 10
      enc[0].encode(obj.contentType, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (!defined(obj.payload)) throw new Error("payload is required")
    buf[offset++] = 18
    enc[1].encode(obj.payload, buf, offset)
    offset += enc[1].encode.bytes
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      contentType: "",
      payload: null
    }
    var found1 = false
    while (true) {
      if (end <= offset) {
        if (!found1) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.contentType = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 2:
        obj.payload = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        found1 = true
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
